
#line 3 "html.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 38
#define YY_END_OF_BUFFER 39
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[262] =
    {   0,
        1,    1,    0,    0,   14,   14,   27,   27,    0,    0,
       39,   36,    1,    1,   21,   33,   34,   22,   37,   37,
       38,   37,   11,   12,   17,   37,   14,   14,   14,   37,
       37,   14,   15,   27,   27,   27,   37,   37,   38,    1,
       21,    0,    0,    0,    0,    0,    9,    0,    9,    9,
        0,    0,    0,   11,   12,   17,    0,   18,   11,   20,
       14,   14,    0,    0,   14,   15,    0,   13,    0,    0,
        0,   16,   27,    0,    0,   27,    0,   30,    0,    0,
        0,    0,    0,   23,    0,    0,    0,    0,    0,    0,
        9,   19,    9,    9,   35,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   31,   24,    0,    0,
        0,    0,    0,    0,    0,    0,   10,   19,    9,    9,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   29,    0,    0,    0,   28,    0,    0,    0,    0,
        0,    0,    0,    9,    9,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    9,    9,    0,    0,    0,    0,    0,    0,    0,
        0,    5,    0,    0,    0,    0,    0,    9,    9,    0,
        0,    0,   25,    0,    0,    0,    6,    0,    5,    0,
        0,    0,    0,    9,    9,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        2,    0,    4,    0,    0,    0,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    4,    0,
        3,    0,    0,    0,    0,    0,    0,   32,    0,    0,
        0,   26,    0,    0,    0,    0,    0,   26,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    7,    0,    8,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    5,    6,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    8,    9,   10,   11,   12,   12,   13,   14,   12,
       12,   12,   12,   12,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   27,
       31,   31,   31,   31,   31,   31,   32,   33,   34,   35,
       31,   31,   31,   36,   31,   31,   31,   31,   37,   31,
       38,   25,   39,   25,   40,   25,   41,   41,   42,   43,

       44,   41,   45,   45,   45,   45,   45,   45,   46,   47,
       48,   49,   45,   45,   45,   50,   45,   45,   45,   51,
       52,   45,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   53,   25,   25,   25,   25,   25,   25,   25,
       25,   54,   54,   54,   54,   54,   54,   54,   54,   54,

       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   25,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   25,   56,   56,   56,
       56,   56,   56,   56,   56
    } ;

static yyconst flex_int32_t yy_meta[57] =
    {   0,
        1,    2,    2,    1,    1,    2,    1,    2,    3,    4,
        5,    6,    1,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   15,    9,    6,   16,   16,   16,   16,   16,
       11,   11,   11,   11,   11,   11,   11,    6,    6,   11,
       16,   16,   16,   16,   11,   11,   11,   11,   11,   11,
       11,   11,    8,   11,   11,   11
    } ;

static yyconst flex_int16_t yy_base[300] =
    {   0,
        0,   39,   78,    0,  133,  155,    9,   11,  914,  913,
      915, 1355,   14,  143,  874,  900,  131,  871, 1355,   53,
      177,  886,    0, 1355, 1355,  885,    0,  200,  210,    5,
       10,  884, 1355,   10,   12,  121,    2,  865, 1355,  187,
      864,  863,    7,  881,  192,   60,    0,    0,  865,  850,
      874,    0,  873,    0, 1355, 1355,  872, 1355,    0, 1355,
        0,  226,   24,   22,  867, 1355,   44, 1355,  249,   51,
      305, 1355,  123,  157,  774,  131,  149,  236,  788,  787,
        9,    0,  789, 1355,  793,  119,  779,  757,  360,  367,
        0,    0,  771,  755, 1355,  354,  405,  449,  500,  153,

      777,  175,  783,  767,  374,  381, 1355, 1355,  772,  173,
      763,  744,  756,  739,  462,  469, 1355,    0,  745,  730,
      361,  547,    0,   59,  191,  579,    0,  460,  759,  743,
      160,  751,  729,  556,  564, 1355,  222,  363,  740,  711,
      686,  708,  660,  677,  659,  682,  679,   60,  666,  666,
      676,  672,  660,  370,  596,  668,  664,  638,  619,  634,
      615,  629,  612,  628,  621,  634,  578,  609,  373,  610,
      624, 1355,  632,  606,  587,  603,  579,  588,  567,  579,
      588,  640, 1355,  584,  376,  650, 1355,  658, 1355,  573,
      551,  547,  538,  666,  674,  552,  535,  530,  474,  473,

      455,  379,  682,  156,  690,  204,  363,  366,  449,  342,
      392,  225,  476,  207,  192,  199,  487,  226,    0,  466,
      382,    0,  579,  177,  452,  459,  158,  698,  706,  114,
      713,  465,  616,  548,  636,  544,   48, 1355,  696,  703,
       28, 1355,  705,  707,   15,  708,  710, 1355,  712,  717,
      724,  720,  728,  729,  757,  767,  781,  731,  791,  733,
     1355,  814,  830,  846,  862,  877,  889,  903,  918,  928,
      944,  960,  976,  992, 1002, 1017, 1027,  170, 1042,  752,
     1057, 1067, 1082, 1098, 1114, 1130, 1146, 1162, 1178, 1194,
     1210, 1226, 1242, 1258, 1274, 1290, 1306, 1322, 1338

    } ;

static yyconst flex_int16_t yy_def[300] =
    {   0,
      262,  262,  261,    3,  263,  263,  264,  264,  265,  265,
      261,  261,  266,  266,  266,  267,  268,  266,  261,  269,
      269,  261,  270,  261,  261,  261,  271,  271,  271,  272,
      273,  271,  261,  274,  274,  274,  274,  274,  261,  266,
      266,  266,  261,  275,  261,  276,  277,  278,  277,  277,
      266,   21,  261,  270,  261,  261,  261,  261,  270,  261,
      271,  271,  272,  273,  271,  261,  272,  261,  261,  273,
      261,  261,  274,  274,  274,  274,  274,  279,  274,  266,
      261,  280,  275,  261,  261,  261,  261,  261,  276,  281,
      277,  282,  277,  277,  261,  272,  261,  273,  261,  274,

      274,  274,  274,  274,  279,  283,  261,  261,  280,  284,
      261,  261,  261,  261,  261,  281,  261,  282,  277,  277,
      272,  272,   97,  272,  273,  273,   99,  273,  274,  274,
      274,  285,  274,  261,  283,  261,  284,  286,  287,  261,
      261,  261,  261,  277,  277,  122,  126,  273,  274,  274,
      285,  288,  274,  284,  289,  287,  290,  261,  261,  261,
      261,  277,  277,  274,  274,  285,  261,  274,  289,  289,
      289,  261,  261,  261,  261,  261,  261,  277,  277,  274,
      274,  261,  261,  274,  289,  289,  261,  261,  261,  261,
      261,  261,  261,  277,  277,  274,  274,  274,  291,  292,

      293,  294,  261,  295,  261,  296,  274,  274,  297,  291,
      261,  292,  261,  293,  293,  294,  261,  295,  298,  295,
      296,  299,  296,  274,  297,  297,  297,  261,  261,  293,
      261,  295,  295,  296,  296,  297,  297,  261,  295,  296,
      297,  261,  295,  296,  297,  295,  296,  261,  295,  296,
      295,  296,  295,  296,  295,  296,  295,  295,  296,  296,
        0,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261

    } ;

static yyconst flex_int16_t yy_nxt[1412] =
    {   0,
       12,   13,   14,   12,   12,   13,   12,   13,  261,  261,
       77,   35,   16,   35,   68,   40,   40,   69,   78,   40,
       17,   40,   71,   68,   81,   36,   81,   36,  108,   37,
       74,   37,   74,   68,   71,   68,   69,  248,   18,   12,
       13,   14,   12,   12,   13,   12,   13,   38,   75,   38,
       75,   16,   42,   68,   52,   52,   69,   82,   52,   17,
       52,   89,   89,   71,   68,   89,  245,   89,   68,   53,
      242,   69,   71,   68,   55,   56,   57,   18,   19,   20,
       21,   19,   19,   20,   19,   20,   19,   19,   19,   19,
       19,   19,   19,   19,   22,   19,   23,   19,   19,   24,

       25,   26,   19,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   19,   19,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       19,   23,   23,   23,   28,   29,  238,   76,   28,   45,
       28,   74,   30,   74,   40,   40,   31,   46,   40,   32,
       40,  102,  111,   19,   48,   33,   28,   29,   49,   75,
       28,   75,   28,  103,   30,  100,  112,  129,   31,   75,
      219,   32,   50,  261,  129,   19,  220,   33,   52,   52,
       92,   42,   52,  131,   52,   92,  104,  138,   40,   40,
      130,  261,   40,   53,   40,  139,  237,  150,   55,   56,

       57,   62,   62,   71,   68,   62,   85,   62,  125,   63,
      128,   62,   62,   64,  209,   62,   65,   62,  222,   63,
       86,  217,   66,   64,  223,   42,   65,   62,   62,   87,
      230,   62,   66,   62,   88,   63,  138,  105,  105,   64,
      219,  105,   65,  105,  139,  215,  220,  213,   66,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   68,   96,
       67,   69,   67,   67,   67,   67,   67,   97,   67,   67,
       67,   67,   67,   67,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   67,   67,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,

       97,   67,   97,   97,   97,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   98,   70,   71,   68,   70,
       70,   70,   70,   99,   70,   70,   70,   70,   70,   70,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   70,   70,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   70,   99,   99,
       99,   89,   89,   68,  211,   89,   69,   89,  115,  115,
       68,  121,  115,   69,  115,  105,  105,  155,  121,  105,
      124,  105,  134,  134,  138,  156,  134,  185,  134,  117,
      171,  224,  139,  228,  228,  261,  222,  228,  261,  228,

      261,  217,  223,  136,  122,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   68,   67,   67,   69,   67,  123,
      123,   67,  123,  123,  124,   67,   67,   67,   67,   67,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,   67,   67,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,   71,   68,  115,  115,  226,  125,  115,  226,  115,
      115,  115,   71,   68,  115,  236,  115,  229,  229,  219,
      219,  229,  233,  229,  117,  220,  220,  227,  231,  231,
      227,  117,  231,  215,  231,  213,  211,  227,  148,  126,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   71,   68,  127,  127,   70,  127,  127,  128,
       70,   70,   70,   70,   70,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,   70,   70,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,   68,  134,  134,   69,
      236,  134,  222,  134,  146,  134,  134,  209,  223,  134,
      208,  134,  146,  146,  146,  146,  146,  207,  136,  182,
      182,  202,  241,  182,  201,  182,  136,  146,  146,  146,
      146,   71,   68,  222,  200,  235,  147,  170,  170,  223,

      183,  170,  199,  170,  147,  147,  147,  147,  147,  198,
      171,  170,  170,  197,  196,  170,  195,  170,  172,  147,
      147,  147,  147,  194,  185,  186,  186,  193,  192,  186,
      219,  186,  172,  188,  188,  191,  220,  188,  171,  188,
      190,  182,  182,  239,  184,  182,  187,  182,  152,  181,
      222,  186,  186,  180,  189,  186,  223,  186,  179,  188,
      188,  178,  183,  188,  185,  188,  177,  203,  203,  176,
      175,  203,  187,  203,  174,  205,  205,  240,  173,  205,
      189,  205,  157,  203,  203,  168,  167,  203,  204,  203,
      152,  205,  205,  165,  164,  205,  206,  205,  128,  228,

      228,  124,  163,  228,  204,  228,  162,  229,  229,  161,
      219,  229,  206,  229,  231,  231,  220,  222,  231,  219,
      231,  222,  219,  223,  222,  220,  219,  223,  220,  243,
      223,  222,  220,  160,  222,  159,  246,  223,  219,  249,
      223,  251,  219,  222,  220,  219,  158,  222,  220,  223,
      244,  220,  247,  223,  157,  250,  253,  153,  257,  257,
      252,  109,  257,  255,  257,  152,  254,  109,  259,  259,
      149,  219,  259,  261,  259,  145,  144,  220,  256,  258,
      143,  222,  257,  257,  142,  141,  257,  223,  257,  260,
      140,  108,  259,  259,  133,  219,  259,  132,  259,  261,

      120,  220,  119,  258,  114,  222,  113,  110,   84,  261,
      107,  223,  101,  260,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   72,
       41,   41,   41,   44,   60,   58,   95,   94,   93,   44,

       84,   80,   42,   79,   44,   47,   72,   60,   58,   51,
       43,   47,   42,   47,  261,   39,   39,  261,   47,   54,
      261,  261,  261,  261,  261,  261,   54,  261,   54,  261,
      261,   54,   54,   54,   59,   59,  261,   59,   59,  261,
      261,  261,  261,   59,   61,  261,   61,  261,   61,   61,
       61,   61,   61,   61,   61,   61,  261,   61,  261,   61,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   73,   73,   73,   73,   73,   73,   73,   73,

       73,   73,   73,   73,   73,   73,   73,   73,   83,   83,
      261,   83,   83,   83,  261,  261,  261,   83,   90,  261,
      261,  261,  261,  261,  261,  261,  261,   90,  261,  261,
      261,  261,   90,   91,   91,  261,   91,   91,  261,  261,
      261,  261,   91,  106,  261,  261,  261,  261,  261,  261,
      261,  261,  106,  261,  261,  261,  261,  106,  116,  261,
      261,  261,  261,  116,  116,  261,  116,  116,  261,  261,
      261,  116,  116,  118,  118,  261,  118,  118,  261,  261,
      261,  261,  118,  135,  261,  261,  261,  261,  135,  135,
      261,  135,  135,  261,  261,  261,  135,  135,  137,  137,

      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  232,  232,  232,  232,  232,  232,  261,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  234,  234,
      234,  234,  234,  234,  261,  234,  234,  234,  234,  234,
      234,  234,  234,  234,   11,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261
    } ;

static yyconst flex_int16_t yy_chk[1412] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    0,    0,
       37,    7,    1,    8,   30,   13,   13,   30,   37,   13,
        1,   13,   31,   31,   43,    7,   81,    8,   81,    7,
       34,    8,   35,   63,   64,   64,   63,  245,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    7,   34,    8,
       35,    2,   13,   67,   20,   20,   67,   43,   20,    2,
       20,   46,   46,   70,   70,   46,  241,   46,  124,   20,
      237,  124,  148,  148,   20,   20,   20,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    5,    5,  230,   36,    5,   17,
        5,   36,    5,   73,   14,   14,    5,   17,   14,    5,
       14,   76,   86,    5,   17,    5,    6,    6,   17,   36,
        6,   73,    6,   77,    6,   74,   86,  100,    6,   76,
      204,    6,   17,   74,  131,    6,  204,    6,   21,   21,
      278,   14,   21,  102,   21,  278,   77,  110,   40,   40,
      100,  102,   40,   21,   40,  110,  227,  131,   21,   21,

       21,   28,   28,  125,  125,   28,   45,   28,  125,   28,
      125,   29,   29,   28,  224,   29,   28,   29,  206,   29,
       45,  216,   28,   29,  206,   40,   29,   62,   62,   45,
      215,   62,   29,   62,   45,   62,  137,   78,   78,   62,
      218,   78,   62,   78,  137,  214,  218,  212,   62,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   89,   89,   96,  210,   89,   96,   89,   90,   90,
      121,   96,   90,  121,   90,  105,  105,  138,  121,  105,
      121,  105,  106,  106,  154,  138,  106,  169,  106,   90,
      185,  208,  154,  211,  211,  169,  221,  211,  185,  211,

      207,  202,  221,  106,   96,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   98,   98,  115,  115,  209,   98,  115,  225,  115,
      116,  116,  128,  128,  116,  226,  116,  213,  213,  232,
      220,  213,  220,  213,  115,  232,  220,  209,  217,  217,
      225,  116,  217,  201,  217,  200,  199,  226,  128,   98,

       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,  122,  134,  134,  122,
      236,  134,  234,  134,  122,  135,  135,  198,  234,  135,
      197,  135,  122,  122,  122,  122,  122,  196,  134,  167,
      167,  193,  236,  167,  192,  167,  135,  122,  122,  122,
      122,  126,  126,  223,  191,  223,  126,  155,  155,  223,

      167,  155,  190,  155,  126,  126,  126,  126,  126,  184,
      155,  170,  170,  181,  180,  170,  179,  170,  155,  126,
      126,  126,  126,  178,  170,  171,  171,  177,  176,  171,
      233,  171,  170,  173,  173,  175,  233,  173,  171,  173,
      174,  182,  182,  233,  168,  182,  171,  182,  166,  165,
      235,  186,  186,  164,  173,  186,  235,  186,  163,  188,
      188,  162,  182,  188,  186,  188,  161,  194,  194,  160,
      159,  194,  186,  194,  158,  195,  195,  235,  157,  195,
      188,  195,  156,  203,  203,  153,  152,  203,  194,  203,
      151,  205,  205,  150,  149,  205,  195,  205,  147,  228,

      228,  146,  145,  228,  203,  228,  144,  229,  229,  143,
      239,  229,  205,  229,  231,  231,  239,  240,  231,  243,
      231,  244,  246,  240,  247,  243,  249,  244,  246,  239,
      247,  250,  249,  142,  252,  141,  243,  250,  251,  246,
      252,  249,  253,  254,  251,  258,  140,  260,  253,  254,
      240,  258,  244,  260,  139,  247,  251,  133,  255,  255,
      250,  280,  255,  253,  255,  132,  252,  280,  256,  256,
      130,  255,  256,  129,  256,  120,  119,  255,  254,  255,
      114,  256,  257,  257,  113,  112,  257,  256,  257,  256,
      111,  109,  259,  259,  104,  257,  259,  103,  259,  101,

       94,  257,   93,  257,   88,  259,   87,   85,   83,   80,
       79,  259,   75,  259,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,   65,
      266,  266,  266,  267,   57,   53,   51,   50,   49,  267,

       44,   42,   41,   38,  267,  268,   32,   26,   22,   18,
       16,  268,   15,  268,   11,   10,    9,    0,  268,  269,
        0,    0,    0,    0,    0,    0,  269,    0,  269,    0,
        0,  269,  269,  269,  270,  270,    0,  270,  270,    0,
        0,    0,    0,  270,  271,    0,  271,    0,  271,  271,
      271,  271,  271,  271,  271,  271,    0,  271,    0,  271,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  275,  275,
        0,  275,  275,  275,    0,    0,    0,  275,  276,    0,
        0,    0,    0,    0,    0,    0,    0,  276,    0,    0,
        0,    0,  276,  277,  277,    0,  277,  277,    0,    0,
        0,    0,  277,  279,    0,    0,    0,    0,    0,    0,
        0,    0,  279,    0,    0,    0,    0,  279,  281,    0,
        0,    0,    0,  281,  281,    0,  281,  281,    0,    0,
        0,  281,  281,  282,  282,    0,  282,  282,    0,    0,
        0,    0,  282,  283,    0,    0,    0,    0,  283,  283,
        0,  283,  283,    0,    0,    0,  283,  283,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  298,  298,  298,  298,  298,  298,    0,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  299,  299,
      299,  299,  299,  299,    0,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "html.l"
#line 4 "html.l"

#include <stdio.h>
#include <string.h>

#include "mensajes.h"
#include "htmlgr.h"
#include "tree.h"

int parser_num_bytes=0;
int parser_num_linea=1;
int is_ascii= 1;

int pre_state= 0;
char script_name[32];

/* funciones internas */
static int cuenta_lineas(char *texto);
static char *trim(char *cad);
static char *trimf(char *cad);
static char *filtcom(char *cad);
static char *comm(char *cad);
static char *cdata_sec(char *str);
static char *etag_val(char *cad);
void lexer_begin_script(char *nombre);
int lexer_end_script(void);

/* counts parsed bytes and lines */
#define YY_USER_ACTION {int i;\
                        parser_num_bytes+= yyleng;\
                        parser_num_linea+= cuenta_lineas(yytext);\
                        if (is_ascii) \
                          for(i=0;yytext[i];i++) \
                            if (yytext[i]<0) is_ascii=0; \
                        }

/* use a custom input module that makes charset convertion */
#define YY_INPUT(buf, result, max_size) \
  result = charset_read(buf, max_size, YY_CURRENT_BUFFER_LVALUE->yy_is_interactive);


#line 909 "html.c"

#define INITIAL 0
#define TAG 1
#define TAG_ATT_VAL 2
#define SCRIPT 3
#define SCRIPT_END 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 77 "html.l"



#line 1104 "html.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 262 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1355 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 80 "html.l"
{if (pre_state) {yylval.cad= yytext; return TOK_CDATA;}
       else {return TOK_WHITESPACE;}}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 83 "html.l"
{yylval.cad=trimf(yytext);return TOK_DOCTYPE;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 84 "html.l"
{yylval.cad=trimf(yytext);return TOK_DOCTYPE;}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 85 "html.l"
{yylval.cad=trimf(yytext);return TOK_DOCTYPE;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 88 "html.l"
{yylval.cad=comm(yytext);return TOK_COMMENT;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 89 "html.l"
{yylval.cad=comm(yytext);return TOK_BAD_COMMENT;}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 90 "html.l"
{yylval.cad=yytext;return TOK_COMMENT;}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 91 "html.l"
{yylval.cad=yytext;return TOK_COMMENT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "html.l"
{yylval.cad= tree_strdup(trim(yytext+1));BEGIN(TAG);return TOK_STAG_INI;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 96 "html.l"
{yylval.cad= tree_strdup(etag_val(yytext)); return TOK_ETAG;} 
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 99 "html.l"
{yylval.cad= tree_strdup(trim(yytext));return TOK_ATT_NAME;}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 100 "html.l"
{BEGIN(TAG_ATT_VAL);return TOK_ATT_EQ;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 101 "html.l"
{BEGIN(TAG);yylval.cad= tree_strdup(filtcom(trim(yytext)));return TOK_ATT_VALUE;}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 102 "html.l"
{BEGIN(TAG);yylval.cad= tree_strdup(trim(yytext));
                      return TOK_ATT_VALUE;}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 104 "html.l"
{BEGIN(0);return TOK_STAG_END;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 105 "html.l"
{BEGIN(0);return TOK_EMPTYTAG_END;}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 106 "html.l"
{BEGIN(0);return TOK_STAG_END;}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 107 "html.l"
{BEGIN(0);return TOK_EMPTYTAG_END;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 109 "html.l"
{yylval.cad= tree_strdup(trim(yytext+2));BEGIN(TAG);return TOK_XMLPI_INI;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 110 "html.l"
{BEGIN(0);return TOK_XMLPI_END;}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 112 "html.l"
{yylval.cad= yytext; return TOK_CDATA;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 113 "html.l"
{yylval.cad= yytext; return TOK_CDATA;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "html.l"
{yylval.cad= tree_strdup(yytext); return TOK_EREF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "html.l"
{yylval.cad= yytext; return TOK_CREF;}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 119 "html.l"
{yylval.cad=comm(yytext);return TOK_CDATA_SEC;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 120 "html.l"
{yylval.cad=cdata_sec(yytext);return TOK_CDATA_SEC;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 121 "html.l"
{yylval.cad= yytext; return TOK_CDATA_SEC;}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 122 "html.l"
{return lexer_end_script();}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 123 "html.l"
{yylval.cad= yytext; return TOK_CDATA_SEC;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 124 "html.l"
{yylval.cad= yytext; return TOK_CDATA_SEC;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 125 "html.l"
{yylval.cad= tree_strdup("\135\135&gt;"); return TOK_CDATA_SEC;}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 127 "html.l"
{yylval.cad=cdata_sec(yytext);return TOK_CDATA_SEC;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 129 "html.l"
{yylval.cad= tree_strdup("&amp;"); return TOK_EREF;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 130 "html.l"
{yylval.cad= tree_strdup("&lt;"); return TOK_EREF;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 131 "html.l"
{yylval.cad= tree_strdup("\135\135&gt;"); return TOK_CDATA;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 133 "html.l"
{DEBUG("carácter descartado");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 135 "html.l"
{/*saxError(yytext);*/INFORM("carácter no emparejado en la entrada");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 138 "html.l"
ECHO;
	YY_BREAK
#line 1403 "html.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(TAG):
case YY_STATE_EOF(TAG_ATT_VAL):
case YY_STATE_EOF(SCRIPT):
case YY_STATE_EOF(SCRIPT_END):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 262 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 262 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 261);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 138 "html.l"



/*
 * cuenta el número de líneas del texto
 *
 */ 
static int cuenta_lineas(char *texto)
{
  int num=0;
  int i;

  for (i=0;texto[i];i++)
    num+= (texto[i]=='\n');

  return num;
}
 
/*
 * filtra los espacios al principio 
 * de una cadena de texto
 *
 */
static char *trim(char *cad)
{
   char *resul= cad;

   /* filtra al principio */
   for ( ;(*resul==0x20)||(*resul==0x0a)||(*resul==0x0d)||(*resul==0x09); 
	resul++);

   return resul;
}

/*
 * filtra los espacios al final 
 * de una cadena de texto
 *
 */
static char *trimf(char *cad)
{
   char *resul= cad;

   if (!(*resul)) return cad;

   for (resul= &cad[strlen(cad)-1] ;
        (resul>cad)&&((*resul==0x20)||(*resul==0x0a)||(*resul==0x0d)||
            (*resul==0x09)); 
	resul--);
   
   /* finaliza la cadena */
   *(resul+1)= 0;

   return cad;
}

/*
 * filtra las comillas al principio y al final de 
 * la cadena de texto que recibe
 *
 */
static char *filtcom(char *cad)
{
  cad[strlen(cad)-1]= 0;
  return cad+1;
} 

/*
 * devuelve el nombre de elemento de un tag de fin de elemento
 *
 */
static char *etag_val(char *cad)
{  
   char *resul= cad+2;
   char *cad2;

   /* filtra al principio */
   for ( ;*resul &&((*resul==0x20)||(*resul==0x0a)||(*resul==0x0d)||
            (*resul==0x09)); resul++);

   cad2= resul;

   /* filtra al final */
   for ( ;*cad2 &&(*cad2!=0x20)&&(*cad2!=0x0a)&&(*cad2!=0x0d)&&
            (*cad2!=0x09)&&(*cad2!='>'); cad2++);

   *cad2= 0;

   return resul;
}

/*
 * devuelve el comentario sacando el marcado,
 * es decir, el texto entre <!-- y el siguiente --
 *
 */
char *comm(char *cad)
{
   char *resul;
   
   if ((resul= strstr(cad+4, "--"))) *resul= 0;

   return cad+4;
}

/*
 * returns a CDATA section without its markup,
 * i.e. without "<![CDATA[" and "]]>"
 * (or "//<![CDATA[" and "//]]>")
 *
 */
char *cdata_sec(char *str)
{
   char *result;
   int len;

   if (str[0] == '/')
      str = &str[11];
   else
      str = &str[9];

   if ((result = strstr(str, "]]>"))) {
      if (*(result - 1) == '/' && *(result - 2) == '/')
         *(result - 2) = 0;
      else
         *(result) = 0;
   } 

   return str;
}

/*
 * establece el estado de SCRIPT
 *
 */
void lexer_begin_script(char *nombre)
{
   strcpy(script_name, nombre);
   DEBUG("comienza script");
   BEGIN(SCRIPT);
}

int lexer_end_script(void)
{
  int i,k;
  char car;

  /* busca el nombre */
  for (i=2; yytext[i] && ((yytext[i]==0x20)||(yytext[i]==0x09)||(yytext[i]==0x0a)
                         ||(yytext[i]==0x0d)); i++); 

  /* sigue hasta el final del nombre */
  for (k=i; yytext[k] && (yytext[k]!=0x20)&&(yytext[k]!=0x09)&&(yytext[k]!=0x0a)
                         &&(yytext[k]!=0x0d)&&(yytext[k]!='>'); k++); 

  car= yytext[k];
  yytext[k]= 0;
  
  if (!strcasecmp(&yytext[i],script_name)) {
    BEGIN(0);
    DEBUG("fin de script");
    yylval.cad= tree_strdup(&yytext[i]);
    return TOK_ETAG;
  } else {
    yytext[k]= car;
    yylval.cad= yytext;
    return TOK_CDATA_SEC;
  }
}

/*
 * Resets the input file for this parser
 *
 */ 
void parser_set_input(FILE *input)
{
  yyin = input;
  yy_flush_buffer(YY_CURRENT_BUFFER);
  BEGIN(0);
}

